version: '3.8'

services:
  reqhub:
    image: ghcr.io/sdlm-technologies/reqhub:latest
    container_name: sdlm-reqhub
    ports:
      - "8080:8080" # Web interface access port
    environment:
      - TZ=Europe/Paris
    volumes:
      # /!\ The left AND right paths MUST BE IDENTICAL.
      # /!\ E.g. - /mnt/pool/music:/mnt/pool/music:rw
      # /!\ This must perfectly match the path that Lidarr knows.
      - /mnt/your_pool/music_folder:/mnt/your_pool/music_folder:rw
      
      # Local folder to save the configuration (URL, API Key, pending tracks)
      - ./data:/app/data
    restart: unless-stopped
